---
development:
  cloud_name: neddinn
  api_key: '358555269189826'
  api_secret: jJZiRszXOelRPoIIYeIayKwzZic
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: neddinn
  api_key: '358555269189826'
  api_secret: jJZiRszXOelRPoIIYeIayKwzZic
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: neddinn
  api_key: '358555269189826'
  api_secret: jJZiRszXOelRPoIIYeIayKwzZic
  enhance_image_tag: true
  static_image_support: false
